# Generated by Django 4.2.13 on 2024-05-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('postDate', models.DateTimeField(auto_now_add=True)),
                ('commentCount', models.IntegerField(default=0)),
                ('author', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blabber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('realName', models.TextField(max_length=100)),
                ('blabName', models.TextField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('numberListeners', models.IntegerField(default=0)),
                ('numberListening', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
