# Generated by Django 4.2.13 on 2024-06-05 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_blabname_user_blab_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='blab',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blab',
            name='id',
        ),
        migrations.AddField(
            model_name='blab',
            name='blabber',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blab',
            name='blabid',
            field=models.IntegerField(default=5, primary_key=True, serialize=False, verbose_name='max_length=11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blab',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
