# Generated by Django 4.2.13 on 2024-06-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_user_remove_blab_author_remove_blab_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('hint', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('real_name', models.CharField(max_length=100, null=True)),
                ('blab_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
