# Generated by Django 4.2.13 on 2024-06-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
