# Generated by Django 4.2.13 on 2024-06-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blabber', models.TextField(max_length=100)),
                ('listener', models.TextField(max_length=100)),
                ('status', models.TextField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'listeners',
            },
        ),
        migrations.CreateModel(
            name='User_History',
            fields=[
                ('eventid', models.IntegerField(primary_key=True, serialize=False)),
                ('blabber', models.TextField(max_length=100)),
                ('event', models.TextField(max_length=250, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'users_history',
            },
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='blabber',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='hint',
            new_name='password_hint',
        ),
        migrations.RemoveField(
            model_name='blab',
            name='commentCount',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='blabid',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='commentid',
            field=models.IntegerField(default=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='blab',
            name='blabber',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blab',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='blab',
            table='blabs',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
